name: CRM Automation Tests

on:
  push:
    branches:
      - master  # You can replace this with the branch you want to run the tests on
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK (Change to your required version if necessary)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Step 3: Cache Maven dependencies to speed up the build
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Install dependencies using Maven
      - name: Install dependencies
        run: mvn install -DskipTests

      # Step 5: Run the tests
      - name: Run automation tests
        run: mvn test

      # Step 6: Archive the test results (Optional)
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/surefire-reports/

